app/Http/routes.php
           'uses'   => 'Admin\Notes\NotesController@destroy',
            'as'    => 'notes.delete'
        ]);


        /*
         * === Search note ====
         */
        Route::get('perfil/{nameFirstName}/notes/search', [
            'uses'  => 'Admin\Notes\NotesController@search',
            'as'    => 'notes.search'
        ]);


        /*
         * === Events ====
         */
        Route::get('perfil/{nameFirstName}/events', [
            'uses'  => 'Admin\Events\EventsController@index',
            'as'    => 'events'
        ]);


        /**
         * === Busquedas ====
         */
        Route::get('search-global/', [
            'uses'  => 'Admin\Search\SearchController@searchGlobal',
            'as'    => 'core.searchGlobal'
        ]);


        // ========   SECCION EMPLEADO   ==========

        Route::get('perfil/{nameFirstName}/empleado/tiendas', [
            'uses'  => 'Admin\Employee\EmployeeController@listEmployeeByUser',
            'as'    => 'empleado.tienda.index'
        ]);

        /*
         * ======= EMPLEADO PRODUCTOS ======
         */

        // LIST PRODUCTS
        Route::get('perfil/{nameFirstName}/tienda/{idEmpresa}/{idTienda}/products', [
            'uses'  => 'Admin\Products\ProductsController@index',
            'as'    => 'empleado.products.index'
        ]);


        Route::post('perfil/{nameFirstName}/products/store', [
            'uses'  => 'Admin\Products\ProductsController@store',
            'as'    => 'products.store'
        ]);

        // Get product
        Route::get('perfil/{nameFirstName}/products/show', [
        'uses'  => 'Admin\Products\ProductsController@show',
        'as'    => 'products.show'
        ]);

        // UPDATE product
        Route::post('perfil/{nameFirstName}/products/update', [
        'uses'   => 'Admin\Products\ProductsController@update',
        'as'    => 'products.update'
    ]);


        /**
         * ========= COMPANY ========
         */

        // SHOW FORM TO CREATE COMPANY OR GET DATA OF COMPANY
        Route::get('admin/{nameFirstName}/companies', [
            'uses'   => 'Admin\Company\CompanyController@index',
            'as'    => 'companies.index'
        ]);

        // CREATE COMPANY
        Route::post('admin/{nameFirstName}/companies/store', [
            'uses'   => 'Admin\Company\CompanyController@store',
            'as'    => 'companies.store'
        ]);

        // SHOW COMPANY
        Route::get('admin/{nameFirstName}/companies/show', [
            'uses'   => 'Admin\Company\CompanyController@show',
            'as'    => 'companies.show'
        ]);

        // UPDATE COMPANY
        Route::post('admin/{nameFirstName}/companies/update', [
            'uses'   => 'Admin\Company\CompanyController@update',
            'as'    => 'companies.update'
        ]);


        /**
         * ========= TIENDAS ========
         */

        // SHOW ALL TIENDAS
        Route::get('admin/{nameFirstName}/stores', [
           'uses'   => 'Admin\Tienda\TiendaController@index',
            'as'    => 'stores.index'
        ]);

        // CREATE TIENDA
        Route::post('admin/{nameFirstName}/stores/store', [
            'uses'  => 'Admin\Tienda\TiendaController@store',
            'as'    => 'stores.store'
        ]);

        // GET TIENDA
        Route::get('admin/{nameFirstName}/stores/show', [
            'uses'  => 'Admin\Tienda\TiendaController@show',
            'as'    => 'stores.show'
        ]);

        // UPDATE TIENDA
        Route::post('admin/{nameFirstName}/stores/update', [
            'uses'  => 'Admin\Tienda\TiendaController@update',
            'as'    => 'stores.update'
        ]);





        /**
         * ========= EMPLEADOS ========
         */

        // SHOW ALL EMPLEADOS
        Route::get('admin/{nameFirstName}/employee', [
            'uses'   => 'Admin\Employee\EmployeeController@index',
            'as'    => 'employee.index'
        ]);

        // NEW EMPLEADO
        Route::post('admin/{nameFirstName}/employee/store', [
            'uses'   => 'Admin\Employee\EmployeeController@store',
            'as'    => 'employee.store'
        ]);

        // GET EMPLEADO
        Route::get('admin/{nameFirstName}/employee/show', [
            'uses'  => 'Admin\Employee\EmployeeController@show',
            'as'    => 'employee.show'
        ]);

        // update
        Route::put('admin/{nameFirstName}/employee/update', [
            'uses'  => 'Admin\Employee\EmployeeController@update',
            'as'    => 'employee.update'
        ]);




    /**
     * ========= PRODUCTOS - administración  ========
     */

    Route::get('admin/{nameFirstName}/products', [
        'uses'  => 'Admin\Products\ProductsAdminController@index',
        'as'    => 'product.admin.index'
    ]);

    Route::get('admin/products/by/store', [
        'uses'  => 'Admin\Products\ProductsAdminController@showByStore',
        'as'    => 'product.admin.by.store'
    ]);


        /**
         * ========= EXTRAS - Categorias, Ofertas y Fabricantes ========
         */

        Route::get('admin/{nameFirstName}/extras', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@index',
            'as'    => 'extras.index'
        ]);

        ///
        // CREATE OFERTA
        Route::post('admin/{nameFirstName}/extras/oferta/store', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@storeOferta',
            'as'    => 'oferta.store'
        ]);

        // GET OFERTA
        Route::get('admin/{nameFirstName}/extras/oferta/show', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@showOferta',
            'as'    => 'oferta.show'
        ]);

        // UPDATE OFERTA
        Route::put('admin/{nameFirstName}/extras/oferta/update', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@updateOferta',
            'as'    => 'oferta.update'
        ]);


        ///
        // CREATE FABRICA
        Route::post('admin/{nameFirstName}/extras/fabrica/store', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@storeFabrica',
            'as'    => 'fabrica.store'
        ]);

        // GET FABRICA
        Route::get('admin/{nameFirstName}/extras/fabrica/show', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@showFabrica',
            'as'    => 'fabrica.show'
        ]);

        // UPDATE FABRICA
        Route::put('admin/{nameFirstName}/extras/fabrica/update', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@updateFabrica',
            'as'    => 'fabrica.update'
        ]);



        ///
        // CREATE CATEGORIA
        Route::post('admin/{nameFirstName}/extras/categoria/store', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@storeCategoria',
            'as'    => 'categoria.store'
        ]);

        // GET CATEGORIA
        Route::get('admin/{nameFirstName}/extras/categoria/show', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@showCategoria',
            'as'    => 'categoria.show'
        ]);

        // UPDATE CATEGORIA
        Route::put('admin/{nameFirstName}/extras/categoria/update', [
            'uses'  => 'Admin\OptionsExtra\OptionExtraController@updateCategoria',
            'as'    => 'categoria.update'
        ]);


    /*
     * ADMIN
     */
    Route::get('admin', [
        'uses'  => 'AdminController@index',
        'as'    => 'panel'
    ]);

    Route::get('admin/{id}/editar', [
        'uses' => 'AdminController@edit',
        'as' => 'admin.edit'
    ]);


    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

        Route::resource('colecciones', 'FormsController');
        Route::resource('complements', 'ComplementsController');
        Route::resource('inputs', 'InputsController');

        // DIBUJAR FORMULARIO
        Route::get('coleccion/{id}/form', [
            'uses'  => 'InputsController@drawForm',
            'as'    => 'form'
        ]);

        // SAVE FORMULARIO
        Route::get('coleccion/form/{id}/new', [
            'uses'  => 'DvarcharController@storeFormData',
            'as'    => 'admin.colecciones.form.data.store'
        ]);

        // SHOW DATA FROM COLLECTION
        Route::get('coleccion/form/{id}/lista', [
            'uses'  => 'DvarcharController@index',
            'as'    => 'admin.colecciones.form.data.index'
        ]);

        // DESTROY ROW DATA
        Route::delete('coleccion/form/lista/row/{id}/delete', [
            'uses'  => 'DvarcharController@destroy',
            'as'    => 'admin.colecciones.form.data.list.destroy'
        ]);

        // SAVE FORMULARIO
        Route::put('coleccion/form/lista/row/{id}/update', [
            'uses'  => 'DvarcharController@update',
            'as'    => 'admin.colecciones.form.data.list.update.input'
        ]);


        /*
         * STATISTIC CONTROLLER
         */

        // VIEW STATISTICS
        Route::get('estadisticas', [
            'uses'  => 'StatisticController@index',
            'as'    => 'admin.statistics.index'
        ]);

        Route::post('estadisticas/colums', [
            'uses'  => 'StatisticController@showColums',
            'as'    => 'admin.statistics.index.columns'
        ]);

        Route::post('estadisticas/colums/data', [
            'uses'  => 'StatisticController@getDataColumns',
            'as'    => 'admin.statistics.index.columns.data'
        ]);

        Route::get('estadisticas/dispersion/puntos/data', [
           'uses'   => 'StatisticController@getPoints' ,
            'as'    => 'statistics.dispersion.puntos.data'
        ]);



        /*
         * EXCEL
         */

        Route::get('export-all', [
            'uses'  => 'ExcelController@exportAll',
            'as'    => 'admin.export.all'
        ]);

        Route::post('{id}/import-all', [
            'uses'  => 'ExcelController@importAllToCollection',
            'as'    => 'admin.import.all'
        ]);

app/Http/Controllers/Admin/ComplementsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Dvarchar;
use App\Form;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class ComplementsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $form = Form::findOrFail($id);
        $existe = Dvarchar::where('form_id', '=', $id)->count();

        return view('admin.colections.complements.builder', compact('form', 'existe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/colections/complements/builder.blade.php
@extends('layout-admin')

@section('title', @trans('title.home'))

@section('content')

    <!-- REVISAR -->
    <div class="head-fixed">
        <div class="head-menu">
            <h1><span><img src="{{ asset('/images/icon-complements.svg') }}"></span> <span> > </span> COMPLEMENTS </h1>
            @include('admin.colections.complements.partials.menu')
        </div>

        <div id="collection-menu">

            @if( $existe <= 0 )
                <button id="btnCorto" class="btn btn-default" title="Agregar nuevo input al formulario" onclick="showModalInputs('modal-textoCorto');"><span><img src="{{ asset('/images/input.svg') }}"></span>Nuevo campo</button>
            @else
                    <h5>* No puedes crear nuevos inputs, debido a que ingresaste registros en BD</h5>
            @endif
                    <!--
            <button id="btnLargo" class="btn btn-default"><span><img src="/images/textarea.svg"></span>Texto largo</button>
            <button id="btnSelect" class="btn btn-default"><span><img src="/images/select.svg"></span>Selección</button>
            <button id="btnOption" class="btn btn-default"><span><img src="/images/option.svg"></span>Opción</button>
            -->
        </div>
    </div>


    {!! Form::open(['route' => ['admin.inputs.show', $form->id], 'method' => 'GET|HEAD', 'id' => 'form-show']) !!}
    {!! Form::close() !!}

    <div class="container-inputs-list max-top" id="datos">

        <!--
        <div class="container-input-base">
            <div>1</div>
            <div>Nombre</div>
            <div><a href="#">Edit</a></div>
            <div><a href="#">Delete</a></div>
        </div>
        -->

    </div>









    @section('complements-builder')
    <div class="notificacion-text-fondo" id="modal-textoCorto" style="display: none">
        <div class="container-builder">
            <div class="builder-form-option">
                <div class="title-input-txt">
                    <span></span>
                    <h2>Texto corto</h2>
                </div>


                {!! Form::open(['route' => 'admin.inputs.store', 'method' => 'POST', 'id' => 'form-textoCorto']) !!}

                <div class="form-group">
                    <label for="title">Título del campo</label>
                    {!! Form::text('title', null, ['id' => 'title', 'class' => 'form-control', 'type' => 'text', 'placeholder' => 'Ingresa un título', 'onkeyup' => 'chagenTitleInput();']) !!}
                </div>

                <div class="form-group">
                    <label for="desc">Decripción del campo</label>
                    {!! Form::textarea('description', null, ['id' => 'description', 'class' => 'form-control', 'placeholder' => 'Ingresa una descripción', 'onkeyup' => 'chagenDescInput();', 'title' => 'Descripción']) !!}
                </div>

                <div class="form-group">
                    <label for="type_validation">Tipo de dato</label>
                    {!! Form::select('type_validation', array(
                        'val_text'      => 'Texto',
                        'val_text_num'  => 'Alfanumerico',
                        'val_num'       => 'Número entero',
                        'val_double'    => 'Numero + decimales',
                        'val_date'      => 'fechas'
                    ), 'alfanumerico', ['id' => 'type_validation']) !!}
                    <!--
                    'val_date' => 'Fecha',
                    'moneda' => 'Moneda',
                    'decimales' => 'Decimales'
                    -->
                </div>

                    {!! Form::hidden('type_input', 'input_text', ['id' => 'type_input', 'class' => 'form-control', 'type' => 'text', 'placeholder' => 'Ingresa un titulo']) !!}
                    {!! Form::hidden('form_id', $form->id, ['id' => 'form_id', 'class' => 'form-control', 'type' => 'text', 'placeholder' => 'Ingresa un titulo']) !!}

                <div class="btn-input-txt">
                    <p>* Este campo será obligatorio</p>
                    <button type="button" class="btn btn-primary" id="registro-textoCorto">GUARDAR</button>
                    <button type="button" class="btn btn-danger" onclick="closeModalInputs('modal-textoCorto');">CANCELAR</button>
                </div>

                {!! Form::close() !!}

            </div>
            <div class="builder-form-preview">

                <h1 id="nav" class="text-center">Vista Previa</h1>

                <div class="form-preview">
                    <div class="form-group">
                        <label for="titleChange" id="titleChangeTo">Título del campo</label><span id="descChangeTo" title="Descripción de este campo." data-toggle="tooltip" data-placement="right" style="margin-left: 5px;"> <img src="{{ asset('/images/icon-help.svg') }}"></span>
                        {!! Form::text('title', null, ['id' => 'titleChange', 'class' => 'form-control', 'type' => 'text', 'disabled', 'placeholder' => 'Contenido']) !!}
                    </div>
                </div>

            </div>
        </div>
    </div>

    @include('partials.alert-ajax')

    @endsection

@endsection

@include('partials.alert-delete')
@include('partials.errors')


{!! Form::open(['route' => ['admin.inputs.destroy', ':USER_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
{!! Form::close() !!}
@section('scripts')
    <script src="{{ asset('/js/codizer-alert.js') }}"></script>
    <script src="{{ asset('/js/inputs.js') }}"></script>
@endsection

resources/views/admin/colections/complements/form.blade.php
@extends('layout-admin')

@section('title', @trans('title.home'))

@section('content')

    <!-- REVISAR -->
    <div class="head-fixed">
        <div class="head-menu">
            <h1><span><img src="{{ asset('/images/icon-complements.svg') }}"></span> <span> > </span> FORMULARIO: {{ $form->name  }}</h1>
            @include('admin.colections.complements.partials.menu')
        </div>
    </div>

    <div class="container-inputs-list min-top">

        <div id="new-register" class="container-form">
            <div class="container-form-titulo">
                <div id="container-form-icon-collection" class="container-form-icon"></div>
                <div><h3>Nuevo registro de {{ $form->name  }}</h3></div>
            </div>

            @if(count($inputs) === 0)

                <p>Aun no generas un formulario, usa > <a href="{{ route('admin.complements.edit', $form) }}">COMPLEMENTS</a></p>

            @else
                {!! Form::open(['route' => ['admin.colecciones.form.data.store', $form], 'method' => 'GET', 'id'=>'save-data']) !!}

                    @foreach($inputs as $input)
                        <div class="form-group">
                            <label for="{{ $input->title }}">{{ $input->title }}</label>
                            {!! Form::text( $input->type_validation . '[]', old('content'), ['id' => $input->title, 'class' => 'form-control form-group-validate ' . $input->type_validation, /*'onkeyup'=>'validacion("'. $input->type_validation .'")',*/ 'title' => $input->description, 'data-toggle' => 'tooltip', 'data-placement' => 'right']) !!}
                            {!! Form::hidden( $input->type_validation . 'x[]', $input->id) !!}
                            {!! Form::hidden( $input->type_validation . 'y[]', $input->title) !!}
                        </div>
                    @endforeach

                <a href="{{ url('/admin/colecciones') }}" class="btn btn-danger">Cancelar</a>
                <button type="submit" class="btn btn-primary">Guardar datos</button>
                <p>* Todos los campos son obligatorios.</p>

                {!! Form::close() !!}

                <!-- <button id="save-data">Validar</button> -->

            @endif

        </div>

        <div id="new-register-import" class="container-form">
            <div class="container-form-titulo">
                <div id="container-form-icon-collection" class="container-form-icon"></div>
                <div><h3>Importar {{ $form->name  }} desde Excel</h3></div>
            </div>

            {!! Form::open(['route' => ['admin.import.all', $form], 'method' => 'POST', 'files' => true]) !!}
            <div class="form-group">
                <label for="doc_excel">Importar documento Excel</label>
                {!! Form::file('file', ['accept'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'required']) !!}
            </div>
            <a href="{{ url('/admin/colecciones') }}" class="btn btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Importar datos</button>
            {!! Form::close() !!}


        </div>

    </div>


@include('partials.alert-ajax')

@endsection

@include('partials.errors')

@section('scripts')
    <script src="{{ asset('/js/codizer-alert.js') }}"></script>
    <script src="{{ asset('/js/codizer-validate.js') }}"></script>
    <script src="{{ asset('/js/form.js') }}"></script>
@endsection

resources/views/admin/colections/complements/listaDatos.blade.php
@extends('layout-admin')

@section('title', @trans('title.home'))

@section('content')

    <!-- REVISAR -->
    <div class="head-fixed">
        <div class="head-menu">
            <h1><span><img src="{{ asset('/images/icon-complements.svg') }}"></span> <span> > </span> GESTIONAR DATOs: COLECCIÓN {{ $form->name  }}</h1>
            @include('admin.colections.complements.partials.menu')
            @include('admin.colections.partials.form-search')
        </div>
    </div>


<div class="container-inputs-list" id="datos">

    @if(count($dTitlesColums) === 0)
        <p>Sin registros > <a href="{{ route('form', $form) }}">NUEVO REGISTRO</a></p>
    @else

        <table class="table table-condensed">
            <thead scope="row">
            <tr>
                <th>#</th>
                @foreach($dTitlesColums as $dTitlesColum)
                    <th style="font-size: 14px;">{{ substr($dTitlesColum->dtitle, 0, 16) . '...' }}</th>
                @endforeach
                    <th>Eliminar</th>
            </tr>
            </thead>
            <tbody>

                @foreach($arrayRows as $arrayRow)
                    <tr>
                        <th scope="row"><h4 style="margin-top: 7px;">{{ $numList++ }}</h4></th>
                        @foreach($arrayRow++ as $row)
                            <td>
                                {!! Form::text('content', $row->content, ['id' => $numList, 'class' => 'form-control input-base ' . $row->type_validation, 'onclick' => 'getVaInput(this);', 'onblur' => 'updateInput(this,'. $row->id .');']) !!}
                            </td>
                            <div style="display: none;">{{ $rowIdDelete = $row->row_id }}</div>
                        @endforeach
                        <td class="text-center">
                            <a href="#" class="input-delete" onclick="eliminarInput(this, {{ $rowIdDelete }} );">
                                <span>
                                    <img src="{{ asset('/images/icon-delete.svg') }}" style="padding-top: 7px;">
                                </span>
                            </a>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    @endif
    </div>

    <div class="listar-data">
        {!! $dTitlesRows->render() !!}
    </div>

    <!--
    <h1>FILAS</h1>
    @foreach($dTitlesRows as $dTitlesRow)
        {{ $dTitlesRow->row_id }}
    @endforeach
        -->


@include('partials.alert-ajax')
@endsection

@include('partials.alert-delete')

{!! Form::open(['route' => ['admin.colecciones.form.data.list.destroy', ':USER_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
{!! Form::close() !!}

{!! Form::open(['route' => ['admin.colecciones.form.data.list.update.input', ':USER_ID'], 'method' => 'PUT', 'id' => 'form-update']) !!}
    {!! Form::text('content', old('content'), ['id' => 'contentUpdate', 'class' => 'form-control']) !!}
{!! Form::close() !!}

@section('scripts')
    <script src="{{ asset('/js/codizer-alert.js') }}"></script>
    <script src="{{ asset('/js/codizer-validate.js') }}"></script>
    <script src="{{ asset('/js/lists.js') }}"></script>
@endsection